19 create incident user story
TeamCharles/customer-service pull request #35
Opened 2016-11-15 21:36 UTC by garrett-vangilder

## Status
**READY**

## Testing

[ ] I have added passing tests for all new functionality.

[X] I have confirmed that all test prior to this pull request still PASS.

## Documentation

[ ] I have fully documented features in this PR's code. Please put an `X` in the box to confirm.

[X ] This PR does **NOT** require documentation.

## Description
A few sentences describing the overall goals of the pull request's commits.

This partially resolves issue number 19. I think that this issue needs to be broken down into smaller issues. So, this one partially resolves the issue at hand.

## Resolves Issue Number

#19 

## Deploy Notes
Notes regarding deployment the contained body of work.  These should note any
db migrations, etc.

```sh
git pull --prune
git checkout 19-create-incident-user-story
dotnet run
```

## Steps to Test or Reproduce
Outline the steps to test or reproduce the PR here.

1. Run the program and add 2 different incidents.
2. You can see that this program works, because the numbers increment properly 

## Impacted Files in Application
List general components of the application that this PR will affect:

* actions/CreateIncidentAction.cs

2016-11-16 16:49 UTC, matthamil requested changes
See comments

2016-11-16 16:49 UTC, matthamil commented on src/customer-service/Actions/CreateIncidentAction.cs
> +            incident.save();
App crashes when a resolution is added and the incident is saved.

2016-11-16 20:24 UTC, garrett-vangilder commented
I'd love to hold off on this till I make some changes.

2016-11-17 19:01 UTC, garrett-vangilder commented
@TeamCharles/team This PR is ready for your review!

2016-11-17 19:03 UTC, matthamil approved these changes

2016-11-17 19:06 UTC, matthamil commented
LGTM 🎸

2016-11-17 20:56 UTC, daynewright requested changes

2016-11-17 20:56 UTC, daynewright commented on src/customer-service/Factories/CustomerFactory.cs
> +            string lastName = fullNameAsArray[1];
This fails if no spaces are entered when submitting the customer name.

2016-11-17 20:56 UTC, daynewright commented on src/customer-service/Actions/CreateIncidentAction.cs
> +            int customerId = customerFactory.getCustomerByFullName(customerName).CustomerId;
We need to check if the customer as entered exists before assigning the id.  If it is typed wrong then this fails.

2016-11-17 20:56 UTC, daynewright commented on src/customer-service/Actions/CreateIncidentAction.cs
> +            int customerId = customerFactory.getCustomerByFullName(customerName).CustomerId;
I think you could do a `try catch`  and fix this?

2016-11-17 21:38 UTC, Anulfo reviewed
LGTM

2016-11-17 21:42 UTC, MattKraatz requested changes
Getting there...

2016-11-17 21:42 UTC, MattKraatz commented on customer-service-tests/CustomerFactoryTests.cs
> +            Assert.NotEmpty(customers);
maybe also assert that the count is greater than 1:
`Assert.True(customers.Count() > 1)` or something like that

2016-11-17 21:42 UTC, MattKraatz commented on src/customer-service/Actions/CreateIncidentAction.cs
> +            List<IncidentType> incidentTypeList = incidentTypeFactory.getAll();
We need the `LabelFactory` here too

2016-11-17 21:42 UTC, MattKraatz commented on src/customer-service/Actions/CreateIncidentAction.cs
> +            IncidentFactory incidentFactory = new IncidentFactory();
It would be more readable to instantiate these factories in the context in which they are used

2016-11-17 21:42 UTC, MattKraatz commented on src/customer-service/Actions/CreateIncidentAction.cs
> +            List<Incident> incidents = incidentFactory.getAll();
What is this used for?

2016-11-17 21:42 UTC, MattKraatz commented on src/customer-service/Actions/CreateIncidentAction.cs
> +            int customerId = customerFactory.getCustomerByFullName(customerName).CustomerId;
You can use linq to query your `customerList` enumerable for a matching FirstName and LastName. Load that into a while loop. No need to hit the database again

2016-11-17 21:42 UTC, MattKraatz commented on src/customer-service/Actions/CreateIncidentAction.cs
> +            int orderID = Convert.ToInt32(orderIDAnswer);
this breaks if the user enters a non-integer

2016-11-17 21:42 UTC, MattKraatz commented on src/customer-service/Actions/CreateIncidentAction.cs
> +            int orderID = Convert.ToInt32(orderIDAnswer);
could use a Try/Catch block here

2016-11-17 21:42 UTC, MattKraatz commented on src/customer-service/Actions/CreateIncidentAction.cs
> +            int orderID = Convert.ToInt32(orderIDAnswer);
basically every time we're waiting for input, that needs to be in a while loop

2016-11-17 21:42 UTC, MattKraatz commented on src/customer-service/Actions/CreateIncidentAction.cs
> +            int incidentTypeId = Convert.ToInt32(incidentTypeIdAnswer);
this breaks if the user enters a non-integer

2016-11-17 21:42 UTC, MattKraatz commented on src/customer-service/Actions/CreateIncidentAction.cs
> +            incident.save();
I don't experience this issue. Must have been resolved with changes.

2016-11-17 21:42 UTC, MattKraatz commented on src/customer-service/Actions/CreateIncidentAction.cs
> +            incident.DateCreated = DateTime.Now;
Need to attach the EmployeeId to the incident.

2016-11-17 21:42 UTC, MattKraatz commented on src/customer-service/Actions/CreateIncidentAction.cs
> +
Need to attach the IncidentTypeId to the Incident

2016-11-17 21:42 UTC, MattKraatz commented on src/customer-service/Actions/CreateIncidentAction.cs
> +            Console.WriteLine($"Incident # {incidents.Count } has been added. Press any key to return to main menu.");
this should be the count + 1, like an auto-incremented value. Basically when I add Incident #5, this WriteLine tells me I added Incident #4

2016-11-17 21:42 UTC, MattKraatz commented on src/customer-service/Actions/CreateIncidentAction.cs
> +                    Console.WriteLine("How was the incident resolved? ");
Need to print a list of all applicable labels here. Check out Dayne's Single Incident PR

2016-11-17 21:42 UTC, MattKraatz commented on src/customer-service/Actions/CreateIncidentAction.cs
> +                    Console.WriteLine("How was the incident resolved? ");
This screen should look exactly like Dayne's, actually. Might help to re-review the requirements in case we're off-base on some other mockups.

2016-11-18 15:25 UTC, garrett-vangilder commented on src/customer-service/Actions/CreateIncidentAction.cs
> +            incident.save();
Changed in previous PR

2016-11-18 15:25 UTC, garrett-vangilder commented on customer-service-tests/CustomerFactoryTests.cs
> +            Assert.NotEmpty(customers);
Added

2016-11-18 15:27 UTC, garrett-vangilder commented on src/customer-service/Actions/CreateIncidentAction.cs
> +            IncidentFactory incidentFactory = new IncidentFactory();
I will change this for the good of the team! 👥

2016-11-18 16:36 UTC, garrett-vangilder commented on src/customer-service/Actions/CreateIncidentAction.cs
> +            List<IncidentType> incidentTypeList = incidentTypeFactory.getAll();
Added

2016-11-18 16:36 UTC, garrett-vangilder commented on src/customer-service/Actions/CreateIncidentAction.cs
> +            List<Incident> incidents = incidentFactory.getAll();
Removed

2016-11-18 16:37 UTC, garrett-vangilder commented on src/customer-service/Actions/CreateIncidentAction.cs
> +            incident.DateCreated = DateTime.Now;
Added

2016-11-18 16:38 UTC, garrett-vangilder commented on src/customer-service/Actions/CreateIncidentAction.cs
> +
added

2016-11-18 16:39 UTC, garrett-vangilder commented on src/customer-service/Actions/CreateIncidentAction.cs
> +            Console.WriteLine($"Incident # {incidents.Count } has been added. Press any key to return to main menu.");
Word, my mistake I thought that the `Count` method was not zero based

this has been added

2016-11-18 18:20 UTC, MattKraatz commented on src/customer-service/Actions/CreateIncidentAction.cs
> +                Console.WriteLine($"{customer.CustomerId} { customer.FirstName} {customer.LastName} ");
How about we leave off `CustomerId` from this WriteLine to eliminate confusion for the user

2016-11-18 18:20 UTC, MattKraatz commented on src/customer-service/Actions/CreateIncidentAction.cs
> +            Console.WriteLine("Enter the customers first and last name to start:");
Let's put this after the list of customers

2016-11-18 18:20 UTC, MattKraatz commented on src/customer-service/Actions/CreateIncidentAction.cs
> +
We need a `Console.ReadLine()` here to start, else the user is shown the "This is not a valid answer. Try again!" right away

2016-11-18 18:20 UTC, MattKraatz commented on src/customer-service/Actions/CreateIncidentAction.cs
> +            while (orderID < 0)
The program never enters this `while` loop as far as I can tell. I think you want: `orderID == 0`

2016-11-18 18:32 UTC, MattKraatz commented on src/customer-service/Actions/CreateIncidentAction.cs
> +
Lose the code below here. Instead, set the `IncidentFactory.Instance.ActiveInstance` to the current instance and the `CustomerFactory.Instance.ActiveCustomer` to the current customer. Then call Dayne's `ShowSingleIncidentAction.ReadLine()`.

2016-11-18 18:33 UTC, MattKraatz commented on src/customer-service/Actions/CreateIncidentAction.cs
> +
NVM

2016-11-18 18:33 UTC, MattKraatz requested changes
A few final changes and we should be good to merge 👍

2016-11-18 18:33 UTC, daynewright approved these changes

2016-11-18 18:34 UTC, daynewright commented
LGTM after @MattKraatz  changes.

2016-11-18 18:51 UTC, garrett-vangilder commented on src/customer-service/Actions/CreateIncidentAction.cs
> +            Console.WriteLine("Enter the customers first and last name to start:");
added

2016-11-18 18:53 UTC, garrett-vangilder commented on src/customer-service/Actions/CreateIncidentAction.cs
> +
changed

2016-11-18 20:52 UTC, MattKraatz approved these changes

2016-11-18 20:58 UTC, merged